### ISSUE TITLE
Can't run the demo

### ISSUE THREAD

**Issue by Ruberik** [muukii/ZoomImageView#11]
I tried to get the demo started so I can work on debugging something that I think might be an issue, but I get an error. Here's what I did:

1. `git clone ...`
2. `rm Podfile.lock`
3. `pod install`  (no errors)
4. `open ZoomImageView.xcworkspace`
5. Select Demo, and hit Run.

I'm using Cocoapods 1.5.3, since 1.6.0 (beta2) doesn't work with some projects.

What I think should happen:
It should run the demo.

What actually happens:
The build fails with four errors. Here's a representative example: `error: /Users/Bartholomew/dev/ZoomImageView/Pods/Pods/Target Support Files/Pods-Demo/Pods-Demo.debug.xcconfig: unable to open file (in target "Demo" in project "ZoomImageView") (in target 'Demo')`

Any thoughts?

**Comment by Ruberik** [comment]
Closing due to age.

**Comment by xavetar** [comment]
Xcode 14 (M1) with iPhone:

1. Install Cocoapods with homebrew.
2. Just clone this project.
3. Go to the cloned folder.
4. Just enter: "pod install".
5. Open with Xcode, enter again: "open ZoomImageView.**xcworkspace**".
6. Set your Sign for both targets with Automatically manage signing.
7. Go to that folder "ZoomImageView/Pods/Reveal-SDK/RevealServer-18/iOS/RevealServer.framework/".
8. Just resign "RevealServer" in this folder: "codesign --deep --force --verbose --sign "$YOUR_SIGN" RevealServer".
9. Finally, just now you can compile this **shit** and run on your device (with simulator this won't run on M1).

Also for Simulator or physical device:

1. Install Cocoapods with homebrew.
2. Just clone this project.
3. Go to the cloned folder.
4. Open with Xcode: "open ZoomImageView.**xcodeproj**".
5. Go to Pods folder in Xcode, open Debug and Release **xcconfig**:
    5.1. Where **OTHER_LDFLAGS** just comment "-framework "RevealServer".
    5.2 Where **FRAMEWORK_SEARCH_PATHS** just comment before.
6. Click on the ZoomImageView in Xcode, go to the target Demo and remove Pods_Demo.framework.
7. Finally, just now you can compile this **shit** and run on your physical device. In this method that's work with Simulator. I think that because dylib from Reveal-SDK is incompatible with Simulator.
